### PR TITLE
fix: google auth example

### LINKED ISSUE #2355: [BUG] Google Auth example outdated
We are trying to build an admin panel using Refine. For the authentication we choose Google OAuth but the popup for Google Authentication is so random. Sometimes it shows up other times it doesn't. We used the skeleton code that is provided by refine cli.

**To Reproduce**
1. Setup refine boilerplate: `npx superplate-cli -p refine-react .`
2. Used settings as follow:
```
✔ Package manager: · yarn
✔ Do you want to use a UI Framework?: · antd
✔ Do you want a customized theme?: · antd-css
✔ Router Provider: · react-location
✔ Data Provider: · data-provider-hasura
✔ Auth Provider: · auth-provider-google
✔ Do you want a customized layout? · no
✔ Do you want to add Kbar command palette: · no
✔ i18n - Internationalization: · no
✔ Would you like to share your choices with us anonymously? · yes

```
3. Setup Google OAuth and whitelist the domain

**Expected behavior**
Google Authentication should work fine. 

**Actual Behavior**
* Popup is so random, sometimes it appears other times `Sign in`  does nothing.
* Errors in console.

**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Firefox, Safari
 - Used dataProvider: Hasura

**Additional context**
On response to my discord comment I am creating this issue.
https://discord.com/channels/837692625737613362/896336798429642785/1011902038822617099

### PR DESCRIPTION
**Pull request by ozkalai**
Google auth example migrated to new Google Identity Services.

### Test plan (required)

This development does not affect any test.

### Closing issues

`closes #2355`

### Self Check before Merge

-   [X] Corresponding issues are created/updated or not needed
-   [X] Docs are updated/provided or not needed
-   [X] Examples are updated/provided or not needed
-   [X] TypeScript definitions are updated/provided or not needed
-   [X] Tests are updated/provided or not needed
-   [X] Changesets are provided or not needed

### CODE REVIEW

File: examples/authProvider/googleLogin/src/pages/login.tsx [hunk 1]
```diff
@@ -1,21 +1,47 @@
 import { useLogin } from "@pankod/refine-core";
-import { AntdLayout, Button, Icons } from "@pankod/refine-antd";
-import { useGoogleLogin, GoogleLoginResponse } from "react-google-login";
-
-const { GoogleOutlined } = Icons;
+import { AntdLayout, Icons } from "@pankod/refine-antd";
+import { useEffect, useRef } from "react";
```
Comment (omeraplak) [inline examples/authProvider/googleLogin/src/pages/login.tsx:3]: order

File: examples/authProvider/googleLogin/src/App.tsx [hunk 2]
```diff
@@ -6,53 +6,59 @@ import {
...
-        clientId,
-        cookiePolicy: "single_host_origin",
-    });
-
     const authProvider: AuthProvider = {
-        login: ({ tokenId, profileObj, tokenObj }: GoogleLoginResponse) => {
+        login: ({ credential }: CredentialResponse) => {
             axios.defaults.headers.common = {
-                Authorization: `Bearer ${tokenId}`,
+                Authorization: `Bearer ${credential}`,
```
Comment (omeraplak) [inline examples/authProvider/googleLogin/src/App.tsx:23]: please follow the official auth provider doc for setting to axios headers
https://refine.dev/docs/core/providers/auth-provider/#setting-authorization-credentials

**Review by omeraplak — APPROVED** [review]
