### PR TITLE
Fix: Antd Pagination with Next.js Links breaks the app

### LINKED ISSUE #1894: [BUG] refine 3.23.2 does not work on nextjs: Multiple children were passed to <Link>
**Describe the bug**

The last version  of refine 3.23.3 does not work with nextjs on list pages

When you try to view to a list page like http://localhost:3000/posts, it failed with this error:

```
Unhandled Runtime Error

Error: Multiple children were passed to <Link> with `href` of `/posts?current=1&pageSize=10` but only one child is supported https://nextjs.org/docs/messages/link-multiple-children 
Open your browser's console to view the Component stack trace.
```

**To Reproduce**
1. Install the refine tutorial with nextjs: npx superplate-cli -p refine-nextjs tutorial
2. Select these options:

```
npx superplate-cli -p refine-nextjs tutorial

✔ Cloned remote source successfully.
✔ What will be the name of your app · tutorial
✔ Do you want to use an UI Framework?: · antd
✔ Do you want to customize theme?: · css
✔ Data Provider: · custom-json-rest-data-provider
✔ Auth Provider: · custom-auth-provider
✔ Do you want to add an example page? · example-resource
✔ Do you want to customize layout? · custom-layout
✔ i18n - Internationalization: · i18n-antd
✔ Would you like to share your choices with us anonymously? · no
```

3. Start refine: npm run dev
4. Go to http://localhost:3000/posts
5. See error

### PR DESCRIPTION
**Pull request by aliemir**
Resolves #1894

### CODE REVIEW

File: packages/core/src/hooks/breadcrumb/index.ts [hunk 1]
```diff
@@ -33,8 +33,7 @@ export const useBreadcrumb = (): UseBreadcrumbReturnType => {
             }
 
             breadcrumbs.push({
-                label:
-                    parentResource.label ?? humanizeString(parentResource.name),
+                label: humanizeString(`${parentResource.name ?? ""}`),
```
Comment (omeraplak) [inline packages/core/src/hooks/breadcrumb/index.ts:36]:
```suggestion
                label: parentResource.label ?? humanizeString(`${parentResource.name ?? ""}`),
```

**Review by ozkalai — APPROVED** [review]
